global.woodTypes = [
    { id: 'oak' },
    { id: 'spruce' },
    { id: 'birch' },
    { id: 'jungle' },
    { id: 'acacia' },
    { id: 'dark_oak' },
    { id: 'mangrove' },
    { id: 'cherry' },
    { id: 'bamboo', raft: true },
    { id: 'crimson', stem: true },
    { id: 'warped', stem: true },
    { id: 'arts_and_crafts:cork' },
    { id: 'vanillabackport:pale_oak' },
    { id: 'natures_spirit:redwood' },
    { id: 'natures_spirit:sugi' },
    { id: 'natures_spirit:wisteria' },
    { id: 'natures_spirit:fir' },
    { id: 'natures_spirit:willow' },
    { id: 'natures_spirit:aspen' },
    { id: 'natures_spirit:maple' },
    { id: 'natures_spirit:cypress' },
    { id: 'natures_spirit:olive' },
    { id: 'natures_spirit:joshua' },
    { id: 'natures_spirit:ghaf' },
    { id: 'natures_spirit:palo_verde' },
    { id: 'natures_spirit:coconut' },
    { id: 'natures_spirit:cedar' },
    { id: 'natures_spirit:larch' },
    { id: 'natures_spirit:mahogany' },
    { id: 'natures_spirit:saxaul' },
    { id: 'enderscape:veiled' },
    { id: 'enderscape:celestial', stem: true },
    { id: 'enderscape:murublight', stem: true },
    { id: 'mynethersdelight:powdery' },
]

global.blacklistedItems = [
    'plushie_buddies:plushie_dark_father',
    'plushie_buddies:plushie_emperor',
    'plushie_buddies:plushie_yoga',
    'plushie_buddies:plushie_chewie',
    'plushie_buddies:plushie_dan_rolo',
    'plushie_buddies:plushie_storm_soldier',

    'create:copycat_step',
    'create:copycat_panel',

    'natures_spirit:whole_pizza',
    'natures_spirit:three_quarters_pizza',
    'natures_spirit:half_pizza',
    'natures_spirit:quarter_pizza',
    'natures_spirit:cheese_bucket',

    'farmersdelight:rope',

    'create_dragons_plus:dragon_breath_bucket',
    'create_dragons_plus:white_dye_bucket',
    'create_dragons_plus:light_gray_dye_bucket',
    'create_dragons_plus:gray_dye_bucket',
    'create_dragons_plus:brown_dye_bucket',
    'create_dragons_plus:red_dye_bucket',
    'create_dragons_plus:orange_dye_bucket',
    'create_dragons_plus:yellow_dye_bucket',
    'create_dragons_plus:lime_dye_bucket',
    'create_dragons_plus:green_dye_bucket',
    'create_dragons_plus:cyan_dye_bucket',
    'create_dragons_plus:light_blue_dye_bucket',
    'create_dragons_plus:blue_dye_bucket',
    'create_dragons_plus:purple_dye_bucket',
    'create_dragons_plus:magenta_dye_bucket',
    'create_dragons_plus:pink_dye_bucket'
]

global.baseColors = [
    '_white_',
    '_light_gray_',
    '_gray_',
    '_black_',
    '_brown_',
    '_red_',
    '_orange_',
    '_yellow_',
    '_lime_',
    '_green_',
    '_cyan_',
    '_light_blue_',
    '_blue_',
    '_purple_',
    '_magenta_',
    '_pink_'
]

global.fullColors = [''].concat(global.baseColors)
global.bleachedColors = ['_bleached_'].concat(global.baseColors)