name = "LabPackDeluxe"
author = "chililisoup"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99f0e76857d998567dd7411595d2d36d6e2dc5ef5953387366cf372e51a441c4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
unsup = "1.1.6"

[options]
no-internal-hashes = true