name = "LabPackDeluxe"
author = "chililisoup"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
unsup = "1.1.6"

[options]
no-internal-hashes = true
