version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "CHECK"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
create_dragons_plus = true
fastitemframes = true
arts_and_crafts = true
farmersdelight = true
plushie_buddies = true
supplementaries = true
create_enchantment_industry = true
spring_to_life = true
fastpaintings = true
suppsquared = true
create = true
amendments = true
creeperoverhaul = true
vanillabackport = true
moyai = true
condiments = true
natures_spirit = true
minecraft = true
exposure = true
